### ISSUE TITLE
Updating issues

### ISSUE THREAD

**Issue by ridds-io** [GDSC-SIT-2024/HacktoberFest-Session24#23]
HTML Comments: The comment block at the beginning is verbose and contains multiple links that could clutter the code. It could be reduced or moved to a separate documentation file.

Invalid HTML Structure: In the back of the card, the <div class= tag is incomplete and missing its class name.

Input Type: The <input type="num"> type is incorrect. It should be type="number".

Input Accessibility: Missing aria-labels or for attributes on inputs can hinder accessibility.

Select Element Options: The expiration year is hardcoded, which will become outdated quickly. This should dynamically update to include the current and future years.

Semantic HTML: Use of div for structural elements could be replaced with more semantic elements for better accessibility and readability.

Button Type: The button should specify type="submit" to ensure form submission behavior.

Code Formatting: Some indentation and spacing issues reduce readability.

**Comment by Soyvor** [comment]
This contains error , please review it once again
